all:
	clear
	@(cd flashphoto_tools_test; make all; ./TOOLTEST)
	@(cd libphoto_filter_test; make all)
	@(cd mia_parser_test; make all)

cleanall:
	@(cd flashphoto_tools_test; make clean)
	@(cd libphoto_filter_test; make clean)
	@(cd mia_parser_test; make clean)
